In [13]:
import torch

x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

y = x + 2
y.requires_grad_(True)
print(y)
print(y.grad_fn)

z = y * y * 3
out = z.mean()
print(out)

out.backward()
print(x.grad)
print(y.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None


In [12]:
a = torch.randn(2, 2) 
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad) 
b = (a * a).sum()
print(b.grad_fn)


False
True
